### PR TITLE
add missing parenthesis

### PR DESCRIPTION
**Pull request by xcodebuild**

### CODE REVIEW

**Comment by FelixHuoEZ** [comment]
Your PR indeed solve my problem partly.
Thx, Sheshen!

**Comment by FelixHuoEZ** [comment]
But Emacs prompt me that there is no function named `org-is-habit-p` which is invoked in funtion `rmh/agendablock-loose-tasks` .
And should it be `parenthesis` in PR message rather than `semicolon`?

**Comment by xcodebuild** [comment]
@saccohuo typo😂 

`org-is-habit-p` is a function of `org-habit`

**Comment by remyhonig** [comment]
Thanks for the PR!

**Pull request merged**
